### ISSUE TITLE
libzmq HANDLE leak

### ISSUE THREAD

**Issue by JulianRooze** [zeromq/clrzmq#131]
We're investigating a process of ours that after a seemingly random time stops working correctly. While that's not necessarily caused by this, we've noticed that the process starts accumulating \BaseNamedObjects\zmq-signaler-port-sync handles that never get released. After about half a day or so, the process had collected about 4500 of them.

Regarding that leak, I found this:

http://lists.zeromq.org/pipermail/zeromq-dev/2013-January/019905.html

http://lists.zeromq.org/pipermail/zeromq-dev/2012-December/019788.html

> “I was referring to a win32 HANDLE leak. I seem to have located the leak.
> zmq::signaler_t::make_fdpair() opens an Event but fails to CloseHandle it.
> Adding the CloseHandle, the handle count for the sample program stays
> constant in task manager.”

When I look at the current libzmq source, I do see a CloseHandle call, and the commit that added it was created on December 27, 2012. 

https://github.com/zeromq/libzmq/blob/master/src/signaler.cpp#L350

As the latest NuGet package of libzmq is before that (November 3, 2012) it doesn't contain that fix yet.

I've tried pulling the latest source for both libzmq en clrzmq and building a new NuGet package for clrzmq that contains the fix, and while both build fine, running build.bat results in a failed test (the others ran fine):

>   Monitor Tests
>     When Monitoring Accepted Event
> C:\code\clrzmq\src\build.proj(80,5): error :
> C:\code\clrzmq\src\build.proj(80,5): error : Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
> C:\code\clrzmq\src\build.proj(80,5): error :    at System.Runtime.InteropServices.Marshal.PtrToStructureHelper(IntPtr ptr, Object structure, Boolean allowValueClasses)
> C:\code\clrzmq\src\build.proj(80,5): error :    at System.Runtime.InteropServices.Marshal.PtrToStructure(IntPtr ptr, Type structureType)
> C:\code\clrzmq\src\build.proj(80,5): error :    at ZeroMQ.Monitoring.ZmqMonitor.Start() in c:\code\clrzmq\src\ZeroMQ\Monitoring\ZmqMonitor.cs:line 142
> C:\code\clrzmq\src\build.proj(80,5): error :    at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
> C:\code\clrzmq\src\build.proj(80,5): error :    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
> C:\code\clrzmq\src\build.proj(80,5): error :    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
> C:\code\clrzmq\src\build.proj(80,5): error :    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
> C:\code\clrzmq\src\build.proj(80,5): error :    at System.Threading.ThreadHelper.ThreadStart()
>       > Should Fire The Accepted Event
> C:\code\clrzmq\src\build.proj(80,5): error MSB3073: The command "C:\code\clrzmq\src\ZeroMQ.AcceptanceTests\bin\x86\Debug\ZeroMQ.AcceptanceTests.exe" exited with code -1073741819.
> Done Building Project "C:\code\clrzmq\src\build.proj" (default targets) -- FAILED.

I'm not sure if I'm doing something wrong (either in building libzmq from source or building clrzmq) or if the last clrzmq code is not compatible yet with the latest libzmq. I suppose a next step is to find the last version of libzmq that was still compatible with clrzmq and applying the CloseHandle fix myself, but I'd rather not.

I built libzmq and clrzmq in Release mode in VS 2010.

**Comment by wjrogers** [comment]
When your program stops working, do you get an error? I have a program that crashes after some time with an access violation that has no stack trace attached to it, and I'm having a hard time figuring out why. I built libzmq from the zeromq-3x repository and clrzmq from this repository.

**Comment by rodaddy** [comment]
I am having the same issue

System.AccessViolationException was unhandled
  HResult=-2147467261
  Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
  Source=clrzmq
  StackTrace:
       at ZeroMQ.Interop.Retry.IfInterrupted[T1,T2,T3,T4](Func`5 operation, T1 arg1, T2 arg2, T3 arg3, T4 arg4) in c:\libs\clrzmq-master\src\ZeroMQ\Interop\Retry.cs:line 26
       at ZeroMQ.Interop.SocketProxy.Send(Byte[] buffer, Int32 size, Int32 flags) in c:\libs\clrzmq-master\src\ZeroMQ\Interop\SocketProxy.cs:line 167
       at ZeroMQ.ZmqSocket.Send(Byte[] buffer, Int32 size, SocketFlags flags) in c:\libs\clrzmq-master\src\ZeroMQ\ZmqSocket.cs:line 738
       at ZeroMQ.ZmqSocket.Send(Byte[] buffer, Int32 size, SocketFlags flags, TimeSpan timeout) in c:\libs\clrzmq-master\src\ZeroMQ\ZmqSocket.cs:line 783
       at ZeroMQ.SendReceiveExtensions.SendFrame(ZmqSocket socket, Frame frame, TimeSpan timeout) in c:\libs\clrzmq-master\src\ZeroMQ\SendReceiveExtensions.cs:line 360
       at ZeroMQ.SendReceiveExtensions.SendFrame(ZmqSocket socket, Frame frame) in c:\libs\clrzmq-master\src\ZeroMQ\SendReceiveExtensions.cs:line 337
       at ZeroMQ.SendReceiveExtensions.SendMessage(ZmqSocket socket, ZmqMessage message) in c:\libs\clrzmq-master\src\ZeroMQ\SendReceiveExtensions.cs:line 478
       at QuoteServer.Server.lastTrade(Double price, String symbol, String ts) in C:\richfieldCSharp\dev\CMEQuoteServer\QuoteServer\Server.cs:line 477
       at QuoteServer.Server.tradeEvent(Object sender, TradeEventArgs e) in C:\richfieldCSharp\dev\CMEQuoteServer\QuoteServer\Server.cs:line 298
       at Onixs.CmeFastHandler.Handler.OnTrade(TradeEventArgs e)
       at ohM=.YRQ=.EhU=(gBU= ExU=, Message FBU=, Group FRU=, Int32 FhU=, String FxU=, DateTime GBU=, DateTime GRU=)
       at ohM=.YRQ=.CRU=(HashSet`1 ChU=, 2hU= CxU=, Message DBU=, Group DRU=, Int32 DhU=, String DxU=, DateTime EBU=, DateTime ERU=)
       at ohM=.YRQ=.BBU=(hRc= BRU=)
       at ohM=.YRQ=.sxQ=(hRc= tBQ=)
       at ohM=.YRQ=.pRQ=(hRc= phQ=, Boolean& pxQ=)
       at ohM=.exU=.ProcessPacket(hRc= packet, Boolean& stopFeed)
       at ohM=.ZBU=.dRU=()
       at ohM=.ZBU=.cxU=()
       at ohM=.ZBU=.cBU=()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException:
