### ISSUE TITLE
SEHException in ZeroMQ.Interop.Retry.IfInterrupted?

### ISSUE THREAD

**Issue by codeoverhaul** [zeromq/clrzmq#163]
Has anyone experienced the exception below? My .NET 4.5 application is using the PUB/SUB pattern, and the exception below is thrown from time to time in the receive loop of my subscriber class.  I'm unable to reproduce it at will, so I'm at a loss. I've also included the receive method from by subscriber class below.

----- Exception ----
System.Runtime.InteropServices.SEHException was unhandled
  HResult=-2147467259
  Message=External component has thrown an exception.
  Source=clrzmq
  ErrorCode=-2147467259
  StackTrace:
       at ZeroMQ.Interop.Retry.IfInterrupted[T1,T2,T3](Func`4 operation, T1 arg1, T2 arg2, T3 arg3)
       at ZeroMQ.Interop.SocketProxy.Receive(Byte[] buffer, Int32 flags, Int32& size)
       at ZeroMQ.ZmqSocket.Receive(Byte[] buffer, SocketFlags flags, Int32& size)
       at ZeroMQ.ExecuteExtensions.WithTimeout[T1,T2,T3,TResult](ZmqSocket socket, ThirdParamOut`4 method, T1 arg1, T2 arg2, T3& arg3, TimeSpan timeout)
       at ZeroMQ.ZmqSocket.Receive(Byte[] buffer, TimeSpan timeout, Int32& size)
       at ZeroMQ.SendReceiveExtensions.Receive(ZmqSocket socket, Encoding encoding, TimeSpan timeout)
       at EPanicButtonReceiver.Classes.ZeroMqSubscriber.ReceiveData()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 

------------------- Receive Method -----------------------
<code>
  private void ReceiveData()
        {
            try
            {
                while (!this.stopEvent.WaitOne(0))
                {
                    var channel = subscriberSocket.Receive(Encoding.UTF8,
                        new TimeSpan(0, 0, 0, 1));

```
                if (string.IsNullOrEmpty(channel))
                {
                    continue;
                }

                lock (this.locker)
                {
                    this.RaiseAlertMessage();
                }
            }
        }
        catch (ZeroMQ.ZmqException ex)
        {
            ELogger.Log(ex.Message);
        }
        finally
        {
            if (subscriberSocket != null)
            {
                subscriberSocket.UnsubscribeAll();
            }

        }
    }
```

</code>

**Comment by tnthao** [comment]
did you ever resolve this issue? i'm seeing the same thing. very hard to reproduce, happens once in a blue moon.

**Comment by mycroes** [comment]
Same for me, our application crashed twice in 4 days, while it has been working without issues (albeit not without occasional restarts on server updates) for something like 4 years. I do have the impression that it's related to network load on the server (max number of open connections perhaps?)
