### ISSUE TITLE
Use of localhost seems to be invalid in connection string

### ISSUE THREAD

**Issue by Capt-Brunch** [zeromq/clrzmq#67]
Using the code from the c# wuclient example in the zGuide, an invalid argument exception is returned on the line "subscriber.Connect("tcp://localhost:5553");". This exception does not occur and the example functions as expected when "localhost" is replaced with "127.0.0.1".

Exception details:

ZMQ.Exception was unhandled
  Message=Invalid argument
  Source=clrzmq
  Errno=22
  StackTrace:
       at ZMQ.Socket.Connect(String addr) in c:\Users\Johnny\Documents\Projects\clrzmq-2.2\src\clrzmq\Socket.cs:line 405
       at ZMQ_Client.Program.Main(String[] args) in C:\Users\Jared\Documents\Visual Studio 2010\Projects\ZMQ Client\ZMQ Client\Program.cs:line 26
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean ignoreSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException:

**Comment by jgoz** [comment]
What version of Windows are you using?

You might have to set up a host alias for localhost -> 127.0.0.1 (in your windows\system32\ets\hosts file). Your version of Windows may not set this by default.

If this situation is common, the zGuide should not use localhost on Windows (127.0.0.1 is preferred). Can you please log this issue there or submit a pull request with the change?

As this is not a clrzmq issue, I am closing this.
